"""Typed surface for the runtime alias to ``app.api._dependencies``."""

from app.api._dependencies import (
    ROLE_PERMISSIONS,
    WEBSOCKET_TOKEN_PROTOCOL,
    Depends,
    HTTPAuthorizationCredentials,
    HTTPBearer,
    HTTPException,
    Request,
    RequireCreateStrategy,
    RequireDeleteStrategy,
    RequireExportBacktest,
    RequireManageUsers,
    RequireRunBacktest,
    RequireUpdateStrategy,
    TokenPayload,
    User,
    WebSocket,
    decode_access_token,
    get_current_user,
    get_current_user_optional,
    get_websocket_current_user,
    has_permission,
    logger,
    logging,
    require_any_permission,
    require_permission,
    security,
    status,
    typing,
)
from app.api._dependencies import _extract_websocket_token as _extract_websocket_token

__all__ = [
    "Depends",
    "HTTPAuthorizationCredentials",
    "HTTPBearer",
    "HTTPException",
    "ROLE_PERMISSIONS",
    "Request",
    "RequireCreateStrategy",
    "RequireDeleteStrategy",
    "RequireExportBacktest",
    "RequireManageUsers",
    "RequireRunBacktest",
    "RequireUpdateStrategy",
    "TokenPayload",
    "User",
    "WEBSOCKET_TOKEN_PROTOCOL",
    "WebSocket",
    "decode_access_token",
    "get_current_user",
    "get_current_user_optional",
    "get_websocket_current_user",
    "has_permission",
    "logger",
    "logging",
    "require_any_permission",
    "require_permission",
    "security",
    "status",
    "typing",
]
